name: "Secret Scan - Gitleaks"

on:
  push:
    # Runs for pushes to all branches
  pull_request:
    branches:
      - main

  # Allows manual execution
  workflow_dispatch:

  # Optional weekly full rescan
  schedule:
    - cron: "0 21 * * 0"   # Monday 02:30 IST

permissions:
  contents: read

jobs:
  gitleaks:
    name: Detect Secrets
    runs-on: ubuntu-latest

    steps:
      # --------------------------------------------------
      # Checkout complete Git history
      # --------------------------------------------------
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      # --------------------------------------------------
      # Scan repository for exposed secrets
      # --------------------------------------------------
      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}